GO
CREATE TABLE [dbo].[HR](
	[MSGV] [nvarchar](20) NOT NULL,
	[Fname] [nvarchar](50) NOT NULL,
	[Lname] [nvarchar](50) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Pass] [varchar](100) NOT NULL,
	[Email] [varchar](100) NULL,
	[Pic] [varbinary](max) NULL,
	[VALID] [bit] NOT NULL,
 CONSTRAINT [PK_HR] PRIMARY KEY CLUSTERED 
(
	[MSGV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO